update=30-May-18 12:28:09 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName2=C:/Program Files/KiCad/share/kicad/library/74xx
LibName3=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName4=C:/Program Files/KiCad/share/kicad/library/actel
LibName5=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName6=C:/Program Files/KiCad/share/kicad/library/allegro
LibName7=C:/Program Files/KiCad/share/kicad/library/Altera
LibName8=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName10=C:/Program Files/KiCad/share/kicad/library/atmel
LibName11=C:/Program Files/KiCad/share/kicad/library/audio
LibName12=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName13=C:/Program Files/KiCad/share/kicad/library/bbd
LibName14=C:/Program Files/KiCad/share/kicad/library/bosch
LibName15=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName16=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName18=C:/Program Files/KiCad/share/kicad/library/conn
LibName19=C:/Program Files/KiCad/share/kicad/library/contrib
LibName20=C:/Program Files/KiCad/share/kicad/library/cypress
LibName21=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName22=C:/Program Files/KiCad/share/kicad/library/device
LibName23=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName24=C:/Program Files/KiCad/share/kicad/library/diode
LibName25=C:/Program Files/KiCad/share/kicad/library/display
LibName26=C:/Program Files/KiCad/share/kicad/library/dsp
LibName27=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName28=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName29=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName30=C:/Program Files/KiCad/share/kicad/library/gennum
LibName31=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName32=C:/Program Files/KiCad/share/kicad/library/hc11
LibName33=C:/Program Files/KiCad/share/kicad/library/infineon
LibName34=C:/Program Files/KiCad/share/kicad/library/intel
LibName35=C:/Program Files/KiCad/share/kicad/library/interface
LibName36=C:/Program Files/KiCad/share/kicad/library/intersil
LibName37=C:/Program Files/KiCad/share/kicad/library/ir
LibName38=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName39=C:/Program Files/KiCad/share/kicad/library/leds
LibName40=C:/Program Files/KiCad/share/kicad/library/LEM
LibName41=C:/Program Files/KiCad/share/kicad/library/linear
LibName42=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName43=C:/Program Files/KiCad/share/kicad/library/maxim
LibName44=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName45=C:/Program Files/KiCad/share/kicad/library/memory
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName52=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName53=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName54=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName55=C:/Program Files/KiCad/share/kicad/library/modules
LibName56=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName57=C:/Program Files/KiCad/share/kicad/library/motorola
LibName58=C:/Program Files/KiCad/share/kicad/library/motors
LibName59=C:/Program Files/KiCad/share/kicad/library/msp430
LibName60=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName61=C:/Program Files/KiCad/share/kicad/library/nxp
LibName62=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName63=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName64=C:/Program Files/KiCad/share/kicad/library/opto
LibName65=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName66=C:/Program Files/KiCad/share/kicad/library/philips
LibName67=C:/Program Files/KiCad/share/kicad/library/power
LibName68=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName69=C:/Program Files/KiCad/share/kicad/library/powerint
LibName70=C:/Program Files/KiCad/share/kicad/library/pspice
LibName71=C:/Program Files/KiCad/share/kicad/library/references
LibName72=C:/Program Files/KiCad/share/kicad/library/regul
LibName73=C:/Program Files/KiCad/share/kicad/library/relays
LibName74=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName75=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName76=C:/Program Files/KiCad/share/kicad/library/sensors
LibName77=C:/Program Files/KiCad/share/kicad/library/silabs
LibName78=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName79=C:/Program Files/KiCad/share/kicad/library/stm8
LibName80=C:/Program Files/KiCad/share/kicad/library/stm32
LibName81=C:/Program Files/KiCad/share/kicad/library/supertex
LibName82=C:/Program Files/KiCad/share/kicad/library/switches
LibName83=C:/Program Files/KiCad/share/kicad/library/texas
LibName84=C:/Program Files/KiCad/share/kicad/library/transf
LibName85=C:/Program Files/KiCad/share/kicad/library/transistors
LibName86=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName87=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName88=C:/Program Files/KiCad/share/kicad/library/valves
LibName89=C:/Program Files/KiCad/share/kicad/library/video
LibName90=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName91=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName92=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName93=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName94=C:/Program Files/KiCad/share/kicad/library/zetex
LibName95=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName96=library/10cl025
LibName97=library/88e1512
LibName98=library/cfps-73
LibName99=library/ksz9021gn
LibName100=library/ksz9021rl
LibName101=library/l829-1j1t-43
LibName102=library/my
LibName103=library/nb3l553
LibName104=library/nup4114upxv6t1g
LibName105=library/tlv62080
[general]
version=1
